# Generated by Django 5.2.15 on 2026-06-22 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del beneficio')),
                ('descripcion', models.TextField(verbose_name='Descripción del beneficio')),
                ('categoria', models.CharField(choices=[('reconocimiento', '🏅 Reconocimiento institucional'), ('academico', '📚 Reconocimiento académico'), ('circular', '🌱 Economía circular'), ('comunidad', '📣 Comunidad y visibilidad')], max_length=20)),
                ('costo_puntos', models.PositiveSmallIntegerField(verbose_name='Costo en puntos')),
                ('gestor', models.CharField(help_text='ej: Coordinacion de Sustentabilidad, biblioteca', max_length=100, verbose_name='quien entrega el beneficio')),
                ('activo', models.BooleanField(default=True)),
                ('nivel_minimo', models.CharField(choices=[('semilla', '🌱 Semilla'), ('brote', '🌿 Brote'), ('arbol', '🌳 Árbol'), ('guardian', '♻️Guardián')], default='semilla', max_length=10, verbose_name='nivel minimo requerido')),
            ],
            options={
                'verbose_name': 'Beneficio',
                'verbose_name_plural': 'Beneficios',
                'ordering': ['costo_puntos'],
            },
        ),
        migrations.CreateModel(
            name='PerfilPuntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos_totales', models.PositiveIntegerField(default=0, verbose_name='Puntos totales acumulados')),
                ('puntos_disponibles', models.PositiveIntegerField(default=0, verbose_name='Puntos disponibles para canjear')),
                ('nivel_actual', models.CharField(choices=[('semilla', '🌱 Semilla'), ('brote', '🌿 Brote'), ('arbol', '🌳 Árbol'), ('guardian', '♻️Guardián')], default='semilla', max_length=10, verbose_name='Nivel actual')),
                ('racha_dias', models.PositiveSmallIntegerField(default=0, verbose_name='Racha de días consecutivos reciclando')),
                ('mejor_racha', models.PositiveSmallIntegerField(default=0, verbose_name='Mejor racha registrada')),
                ('ultimo_deposito', models.DateField(blank=True, null=True, verbose_name='Último dia de deposito')),
            ],
            options={
                'verbose_name': 'Perfil de Puntos',
                'verbose_name_plural': 'Perfiles de Puntos',
            },
        ),
        migrations.CreateModel(
            name='Canje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', '⏳ Pendiente de aprobación'), ('aprobado', '✅ Aprobado'), ('rechazado', '❌ Rechazado'), ('entregado', '🎁 Entregado')], default='pendiente', max_length=10)),
                ('puntos_descontados', models.PositiveSmallIntegerField(verbose_name='puntos descontados')),
                ('codigo_canje', models.UUIDField(blank=True, null=True, verbose_name='Codigo QR de canje')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('beneficio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='canjes', to='puntos.beneficio', verbose_name='beneficio solicitado')),
            ],
            options={
                'verbose_name': 'Canje',
                'verbose_name_plural': 'Canjes',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
