# Generated by Django 5.2.15 on 2026-06-22 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contenedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del contenedor')),
                ('area', models.CharField(choices=[('casino', 'Casino'), ('gastronomia', 'Gastronomica'), ('punto_verde', 'Punto Verde'), ('salud', 'Salud'), ('locales_comida', 'Locales de Comida')], max_length=30, verbose_name='Área del campus')),
                ('tipo_residuo', models.CharField(choices=[('organico', 'Organico'), ('inorganico', 'Inorganico / reciclable'), ('papel', 'Papel  y carton'), ('mixto', 'Mixto'), ('compost', 'Compostera')], max_length=30, verbose_name='Tipo de residuo')),
                ('codigo_qr', models.UUIDField(editable=False, unique=True, verbose_name='Código QR')),
                ('altura_cm', models.PositiveSmallIntegerField(default=100, verbose_name='Altura del interior del contenedor (cm)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_instalacion', models.DateField(auto_now_add=True, verbose_name='Fecha de instalación')),
            ],
            options={
                'verbose_name': 'Contenedor',
                'verbose_name_plural': 'Contenedores',
                'ordering': ['area', 'tipo_residuo'],
            },
        ),
        migrations.CreateModel(
            name='RegistroResiduos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Peso del residuo (kg)')),
                ('peso_automatico', models.BooleanField(default=False, verbose_name='Peso registrado automáticamente')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora del registro')),
                ('puntos_obtenidos', models.PositiveIntegerField(default=0, verbose_name='Puntos obtenidos')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('contenedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='residuos.contenedor', verbose_name='Contenedor')),
            ],
            options={
                'verbose_name': 'Registro de Residuo',
                'verbose_name_plural': 'Registros de Residuos',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
