# Generated by Django 5.2.15 on 2026-06-22 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residuos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaContenedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('aviso', 'Aviso(80%)'), ('critico', 'Urgente(95%)')], max_length=10, verbose_name='Nivel de alerta')),
                ('porcentaje_al_momento', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Porcentaje de llenado al momento de la alerta')),
                ('atendida', models.BooleanField(default=False, verbose_name='Alerta atendida')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora de creación')),
                ('fecha_atencion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de atención')),
                ('notificado_municipalidad', models.BooleanField(default=False, verbose_name='municipalidad notificado')),
                ('contenedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='residuos.contenedor', verbose_name='Contenedor')),
            ],
            options={
                'verbose_name': 'Alerta de Contenedor',
                'verbose_name_plural': 'Alertas de Contenedores',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='LecturaSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Distancia_cm', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Distancia medida (cm)')),
                ('porcentaje_llenado', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Porcentaje de llenado (%)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora de la lectura')),
                ('token_dispositivo', models.CharField(max_length=64, verbose_name='Token del dispositivo')),
                ('contenedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='residuos.contenedor', verbose_name='Contenedor')),
            ],
            options={
                'verbose_name': 'Lectura del Sensor',
                'verbose_name_plural': 'Lecturas de los Sensores',
                'ordering': ['-timestamp'],
            },
        ),
    ]
